---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-06b21ccaeff8cd686
      InstanceType: t2.micro
