AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for EC2 instance'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

Conditions:
  IsProd: !Equals
    - !Ref Environment
    - prod
  IsStaging: !Equals
    - !Ref Environment
    - staging
  IsDev: !Equals
    - !Ref Environment
    - dev

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c614dee691cbbf37
    us-east-2:
      AMI: ami-018875e7376831abe
  SizeMap:
    t2.micro:
      InstanceType: 't2.micro'
    t2.small:
      InstanceType: 't2.small'
    t2.medium:
      InstanceType: 't2.medium'

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !If
        - IsProd
        - !FindInMap [SizeMap, t2.medium, InstanceType]
        - !If
          - IsStaging
          - !FindInMap [SizeMap, t2.small, InstanceType]
          - !FindInMap [SizeMap, t2.micro, InstanceType]
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      AvailabilityZone: 'us-east-1a'
      SecurityGroups:
        - !ImportValue SSHSecurityGroup
